# Generated by Django 4.2.3 on 2023-07-19 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.CharField(max_length=55, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('authors', models.TextField()),
                ('published_date', models.CharField(max_length=10)),
                ('categories', models.TextField()),
                ('average_rating', models.FloatField()),
                ('ratings_count', models.IntegerField()),
                ('thumbnail', models.URLField()),
            ],
        ),
    ]
